### ISSUE TITLE
yii\base\InvalidConfigException: Failed to instantiate component or class 

### ISSUE THREAD

**Issue by chadcrowell** [KuriousAgency/commerce-bundles#6]
I have been getting an error on production when I go to the bundles plugin, but not on dev.

Craft CMS 3.5.11.1
Bundles 1.1.4

Local is php 7.3.15
Production is php 7.4.11

Any idea what this error means?

```
Next yii\base\InvalidConfigException: Failed to instantiate component or class "kuriousagency\commerce\bundles\assetbundles\bundles\BundlesAsset". in /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/di/Container.php:455
Stack trace:
#0 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/di/Container.php(380): yii\di\Container->getDependencies('kuriousagency\\c...')
#1 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('kuriousagency\\c...', Array, Array)
#2 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('kuriousagency\\c...', Array, Array)
#3 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/web/AssetManager.php(264): yii\BaseYii::createObject(Array)
#4 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/web/AssetManager.php(237): yii\web\AssetManager->loadBundle('kuriousagency\\c...', Array, true)
#5 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('kuriousagency\\c...')
#6 /srv/users/scradmin/apps/production/vendor/twig/twig/src/Extension/CoreExtension.php(1499): yii\web\View->registerAssetBundle('kuriousagency\\c...')
#7 /srv/users/scradmin/apps/production/vendor/craftcms/cms/src/helpers/Template.php(92): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#8 /srv/users/scradmin/apps/production/storage/runtime/compiled_templates/8c/8cecc20069d7eea9227d7bfb2038b047de843f83154739e1ee336f778d9a963c.php(96): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#9 /srv/users/scradmin/apps/production/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e9210a7d670ee12fade609d193f1fea50d2c47707b56f702aa540d8afcca5a18->doDisplay(Array, Array)
#10 /srv/users/scradmin/apps/production/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /srv/users/scradmin/apps/production/storage/runtime/compiled_templates/c6/c64ec0ecb1bd71dae8d92f328a72937215c14ad327baad6526860a66b6e99df9.php(38): Twig\Template->display(Array)
#12 /srv/users/scradmin/apps/production/vendor/twig/twig/src/Template.php(405): __TwigTemplate_39ec66be56c751b70eb3fc1f098dbbc180edba51e11cc13ebcd923d88db11724->doDisplay(Array, Array)
#13 /srv/users/scradmin/apps/production/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /srv/users/scradmin/apps/production/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#15 /srv/users/scradmin/apps/production/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#16 /srv/users/scradmin/apps/production/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#17 /srv/users/scradmin/apps/production/vendor/craftcms/cms/src/web/View.php(392): Twig\Environment->render('commerce-bundle...', Array)
#18 /srv/users/scradmin/apps/production/vendor/craftcms/cms/src/web/View.php(453): craft\web\View->renderTemplate('commerce-bundle...', Array)
#19 /srv/users/scradmin/apps/production/vendor/craftcms/cms/src/web/Controller.php(251): craft\web\View->renderPageTemplate('commerce-bundle...', Array, 'cp')
#20 /srv/users/scradmin/apps/production/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('commerce-bundle...', Array)
#21 [internal function]: craft\controllers\TemplatesController->actionRender('commerce-bundle...', Array)
#22 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#24 /srv/users/scradmin/apps/production/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('render', Array)
#25 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#26 /srv/users/scradmin/apps/production/vendor/craftcms/cms/src/web/Application.php(285): yii\base\Module->runAction('templates/rende...', Array)
#27 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#28 /srv/users/scradmin/apps/production/vendor/craftcms/cms/src/web/Application.php(270): yii\web\Application->handleRequest(Object(craft\web\Request))
#29 /srv/users/scradmin/apps/production/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /srv/users/scradmin/apps/production/public_html/index.php(21): yii\base\Application->run()
#31 {main}
2020-11-03 20:49:36 [-][1][cf243396014b66b91edfb57a49f12323][info][application] $_GET = [
    'p' => 'admin/commerce-bundles'
]
```

**Comment by chadcrowell** [comment]
Updated to 1.1.6 and fixed.
